import { useRef, useState } from 'react';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { Linking, Text } from 'react-native';
import { Body, Button, Card, Chips, ErrorText, Label, Page, s } from '@/ui';
import { foodGear, foodIdeas } from '@/outdoor-ideas';
import { useStore } from '@/store';

export default function Food(){
 const router=useRouter(),{tripId,loadoutId}=useLocalSearchParams<{tripId?:string;loadoutId?:string}>(),{state,commit,saving}=useStore();
 const [destination,setDestination]=useState(loadoutId?'Loadout':tripId?'Trip':'Locker'),[target,setTarget]=useState(loadoutId||tripId||''),[error,setError]=useState(''),[message,setMessage]=useState('');const working=useRef(false);
 async function add(id:string){if(working.current)return;working.current=true;setError('');setMessage('');try{await commit(s=>{const list=destination==='Trip'?s.trips.find(t=>t.id===target)?.items:destination==='Loadout'?s.loadouts.find(l=>l.id===target)?.items:s.gear;if(!list)throw Error('Choose a trip or loadout first.');const gear=foodGear(id);if(list.some(g=>g.slot===gear.slot))throw Error('This food idea is already here. Edit its quantity instead.');gear.owned=destination==='Locker';list.push(gear);return s;});setMessage('Food idea added. Open its gear details to enter portion weight, calories and quantity.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{working.current=false;}}
 return <Page><Stack.Screen options={{title:'Food & snack ideas'}}/><Label>FUEL YOUR ADVENTURE</Label><Text style={s.title}>Food & snack ideas</Text><Body>Start with foods you already enjoy. Try a new recipe before a trip, check allergens, and pack water and any preparation fuel. These are suggestions; portion size and calories depend on your own ingredients.</Body>
 <Card><Text style={s.h2}>Add to your packing setup</Text><Chips values={['Locker','Trip','Loadout']} value={destination} onChange={v=>{setDestination(v);setTarget('');setMessage('');}}/>{destination==='Trip'?state.trips.map(t=><Button key={t.id} secondary title={(target===t.id?'Selected: ':'Choose trip: ')+t.name} onPress={()=>setTarget(t.id)}/>):destination==='Loadout'?state.loadouts.map(l=><Button key={l.id} secondary title={(target===l.id?'Selected: ':'Choose loadout: ')+l.name} onPress={()=>setTarget(l.id)}/>):null}{destination==='Trip'&&!state.trips.length?<Button secondary title="Build a trip" onPress={()=>router.push('/trip/new')}/>:null}{destination==='Loadout'&&!state.loadouts.length?<Button secondary title="Create a loadout" onPress={()=>router.push('/loadouts')}/>:null}<ErrorText message={error}/>{message?<Text accessibilityRole="alert" style={s.body}>{message}</Text>:null}</Card>
 {foodIdeas.map(idea=><Card key={idea.id}><Text style={s.h2}>{idea.name}</Text><Body>{idea.recipe}</Body><Button title={'Add '+idea.name} onPress={()=>void add(idea.id)} disabled={saving||destination!=='Locker'&&!target}/></Card>)}
 <Card><Label>PACK AND STORE FOOD SAFELY</Label><Body>Keep dry foods protected from moisture and pests. Keep perishable food cold and follow its package directions. Store food and trash according to local wildlife rules.</Body><Button secondary title="USDA outdoor food safety guide" onPress={()=>void Linking.openURL('https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/food-safety-while-hiking-camping').catch(()=>setError('Could not open the food safety guide.'))}/></Card>
 <Button secondary title="Browse food products and source links" onPress={()=>router.push({pathname:'/catalog',params:{category:'Food & nutrition'}})}/><Body>Catalog website links are ordinary source links. No referral discount, affiliate relationship or commission has been verified.</Body>
 </Page>;
}
