import { Text } from 'react-native';
import { Body, Card, Label, Page, s } from '@/ui';
export default function Privacy() {
 return <Page><Label>HUNTEROS / PRIVACY & DATA</Label><Text style={s.title}>Your plans and your choices.</Text>
 <Card><Text style={s.h2}>Use it without an account</Text><Body>Trips, gear, packing status, favorites and scan history are saved on this device. An account is optional. Signing out leaves this device's workspace in place.</Body></Card>
 <Card><Text style={s.h2}>Optional account and cloud backup</Text><Body>Creating an account sends your email and password to Supabase for authentication. When you choose Upload, your workspace goes to the HunterOS Supabase project. It includes trip notes, any locations you entered, gear, favorites and scan history. Your backup is restricted to your account by database access rules; the app operator also administers the backend. Upload replaces your previous cloud copy. Restore replaces your device copy after confirmation. Changes do not merge automatically between devices.</Body></Card>
 <Card><Text style={s.h2}>Camera and barcode lookup</Text><Body>The scanner uses the camera to read a code. HunterOS does not upload camera video or photos. Codes and matched product details are saved locally. A numeric UPC/EAN code may be sent to Open Food Facts to identify packaged food; that service also receives normal connection information such as your IP address. Other codes can be saved manually for you to identify.</Body></Card>
 <Card><Text style={s.h2}>Photos and outside links</Text><Body>Catalog photos load from external image providers. Those providers receive normal connection information, such as your IP address and the requested image. Product links open outside websites with their own privacy practices. Your saved notes and gear lists are not attached to those requests.</Body></Card>
 <Card><Text style={s.h2}>Backups and feedback you share</Text><Body>Exported files include your workspace, including notes, locations and scan history. Choose where to save or share them carefully. Feedback prepares your message, app version and device platform for sharing through an app you choose. Trips and gear are not attached automatically.</Body></Card>
 <Card><Text style={s.h2}>Keeping and removing data</Text><Body>Local data remains until you edit it, replace it with an import or restore, or remove the app's data. Uninstalling can erase local plans but does not delete your cloud account or backup. Manage exported copies and operating-system backups separately. During this private beta, contact support@gethunteros.com to request removal of your cloud account and data.</Body></Card>
 <Card><Text style={s.h2}>Questions during the beta</Text><Body>Open Settings, then Send feedback. You can review the message before choosing a recipient. This screen describes the private beta; the public release privacy policy is still being prepared.</Body></Card>
 </Page>;
}
