import { Text } from 'react-native';
import { Body, Card, Label, Page, s } from '@/ui';
export default function Privacy() {
 return <Page><Label>HUNTEROS / PRIVACY & DATA</Label><Text style={s.title}>Your plans and your choices.</Text>
 <Card><Text style={s.h2}>Use it without an account</Text><Body>Trips, gear, packing status, favorites and scan history are saved on this device. An account is optional. Signing out leaves this device's workspace in place.</Body></Card>
 <Card><Text style={s.h2}>Optional account and cloud backup</Text><Body>Creating an account sends your email and password to Supabase for authentication. When you choose Upload, your workspace goes to the HunterOS Supabase project. It includes trip notes, any locations you entered, gear, favorites and scan history. Your backup is restricted to your account by database access rules; the app operator also administers the backend. Upload replaces your previous cloud copy. Restore replaces your device copy after confirmation. Changes do not merge automatically between devices.</Body></Card>
 <Card><Text style={s.h2}>Camera and barcode lookup</Text><Body>The scanner uses the camera to read a code. HunterOS does not upload camera video or photos. Codes and matched product details are saved locally. A numeric UPC/EAN code may be sent to Open Food Facts to identify packaged food; that service also receives normal connection information such as your IP address. Other codes can be saved manually for you to identify.</Body></Card>
 <Card><Text style={s.h2}>Products shared with everyone</Text><Body>When you choose Use picture and share product with everyone, HunterOS sends the manufacturer product link and selected category to its Supabase server. The server reads the public manufacturer page and adds its product name, brand, picture link and source to the shared catalog. Your personal gear name, notes, measured weight, price paid, quantity and trips are not published. A private contribution record links the product to your account for support and abuse handling. Shared entries remain available to other people; contact support@gethunteros.com for corrections or removal. Product importing requires a verified account and is limited to supported manufacturers.</Body></Card>
 <Card><Text style={s.h2}>Photos and outside links</Text><Body>Catalog photos load from external image providers. Those providers receive normal connection information, such as your IP address and the requested image. Product links open outside websites with their own privacy practices. Your saved notes and gear lists are not attached to those requests.</Body></Card>
 <Card><Text style={s.h2}>Backups and feedback you share</Text><Body>Exported files include your workspace, including notes, locations and scan history. Choose where to save or share them carefully. Send feedback stores your notes, optional reply email, app version, device platform and signed-in account identifier in HunterOS's private Supabase feedback log. No account is required. The owner and tools they authorize can review and summarize reports to improve the app. Trips, gear and passwords are not included. A received report can also be copied into email or text; screenshots added there stay in that separate message.</Body></Card>
 <Card><Text style={s.h2}>Feedback records</Text><Body>Unsent reports are kept on this device for manual retry; the app does not send them in the background. Up to 50 recent report records stay here. Received reports stay in the private feedback log for review and fix tracking. You can request removal at support@gethunteros.com using the report reference. Removing this app's data does not remove a received server report.</Body></Card>
 <Card><Text style={s.h2}>Keeping and removing data</Text><Body>Local data remains until you edit it, replace it with an import or restore, or remove the app's data. Uninstalling can erase local plans but does not delete your cloud account or backup. Manage exported copies and operating-system backups separately. During this private beta, contact support@gethunteros.com to request removal of your cloud account and data.</Body></Card>
 <Card><Text style={s.h2}>Questions during the beta</Text><Body>Open Settings, then Send feedback. You can review your notes before sending them to HunterOS. This screen describes the private beta; the public release privacy policy is still being prepared.</Body></Card>
 </Page>;
}
