import { Text } from 'react-native';
import { Body, Card, Label, Page, s } from '@/ui';
import { AccountDataLinks } from '@/policy-links';
export default function Privacy() {
 return <Page><Label>HUNTEROS / PRIVACY & DATA</Label><Text style={s.title}>Your plans and your choices.</Text>
 <Card><Text style={s.h2}>Use it without an account</Text><Body>Trips, gear, packing status, favorites and scan history are saved on this device. An account is optional. Signing out leaves this device's workspace in place.</Body></Card>
 <Card><Text style={s.h2}>Optional account and cloud backup</Text><Body>Creating an account sends your email and password to Supabase for authentication. When you choose Upload, your workspace goes to the HunterOS Supabase project. It includes trip notes, any locations you entered, gear, favorites and scan history. Your backup is restricted to your account by database access rules; the app operator also administers the backend. Upload replaces your previous cloud copy. Restore replaces your device copy after confirmation. Changes do not merge automatically between devices.</Body></Card>
 <Card><Text style={s.h2}>Your user ID, friends and groups</Text><Body>Every account receives a permanent eight-digit user ID and an editable display name. Someone who knows your user ID or exact account email can send you a friend request. You choose whether to accept or decline. There is no public user directory, and the app does not show your email to other people. Your name, ID, connections, invitations, blocks, group memberships and shared gear posts are stored in HunterOS's Supabase project. Accepted friends can see friends-only posts; accepted group members can see that group's posts and members. Trips, locations, locker contents and backups are not shared by these features.</Body></Card>
 <Card><Text style={s.h2}>Private messages</Text><Body>Accepted friends can send one-to-one text messages. Message text, sender and recipient IDs, timestamps, and your reading position are stored in HunterOS's Supabase project. Conversation access is limited to its two participants through the app; the app operator administers the backend. Messages are not end-to-end encrypted. Messages refresh while the screen is open. This version does not send push or email notifications for messages.</Body></Card>
 <Card><Text style={s.h2}>Control what you share</Text><Body>Removing a friend stops new messages and access to friends-only posts. Previous messages remain readable; shared groups remain separate. Blocking removes the friendship, stops new messages and requests, and hides your conversation and posts from each other, including in groups. Unblocking does not restore the friendship. Leaving or being removed from a group deletes your posts in that group. Report a problem from Friends or contact support@gethunteros.com. Recipients may have saved copies of what you previously shared. Account deletion removes your messages and associated reading records from the active database.</Body></Card>
 <Card><Text style={s.h2}>Recommendations and Popular</Text><Body>Recommended uses saved gear categories on this device. Choosing I like this or I use this stores that product choice with your account and contributes to public product totals only when at least three people have contributed to that product. Public totals do not include names or account identifiers. You can withdraw each choice from the product page. These choices do not post to friends. New releases use separately verified product release dates and sources.</Body></Card>
 <Card><Text style={s.h2}>Camera and barcode lookup</Text><Body>The scanner uses the camera to read a code. HunterOS does not upload camera video or photos. Codes and matched product details are saved locally. A numeric UPC/EAN code may be sent to Open Food Facts to identify packaged food; that service also receives normal connection information such as your IP address. Other codes can be saved manually for you to identify.</Body></Card>
 <Card><Text style={s.h2}>Products shared with everyone</Text><Body>When you choose Use picture and share product with everyone, HunterOS sends the manufacturer product link and selected category to its Supabase server. The server reads the public manufacturer page and adds its product name, brand, picture link and source to the shared catalog. Your personal gear name, notes, measured weight, price paid, quantity and trips are not published. A private contribution record links the product to your account for support and abuse handling. Shared entries remain available to other people; contact support@gethunteros.com for corrections or removal. Product importing requires a verified account and is limited to supported manufacturers.</Body></Card>
 <Card><Text style={s.h2}>Photos and outside links</Text><Body>Catalog photos load from external image providers. Those providers receive normal connection information, such as your IP address and the requested image. Product links open outside websites with their own privacy practices. Your saved notes and gear lists are not attached to those requests.</Body></Card>
 <Card><Text style={s.h2}>Backups and feedback you share</Text><Body>Exported files include your workspace, including notes, locations and scan history. Choose where to save or share them carefully. Send feedback stores your notes, optional reply email, app version, device platform and signed-in account identifier in HunterOS's private Supabase feedback log. No account is required. The owner and tools they authorize can review and summarize reports to improve the app. Trips, gear and passwords are not included. A received report can also be copied into email or text; screenshots added there stay in that separate message.</Body></Card>
 <Card><Text style={s.h2}>Feedback records</Text><Body>Unsent reports are kept on this device for manual retry; the app does not send them in the background. Up to 50 recent report records stay here. Received reports stay in the private feedback log for review and fix tracking. You can request removal at support@gethunteros.com using the report reference. Removing this app's data does not remove a received server report.</Body></Card>
 <Card><Text style={s.h2}>Keeping and removing data</Text><Body>Local data remains until you edit it, replace it with an import or restore, or remove the app's data. Uninstalling can erase local plans but does not delete your cloud account or backup. Manage exported copies and operating-system backups separately. During this private beta, contact support@gethunteros.com to request removal of your cloud account and data.</Body></Card>
 <Card><Text style={s.h2}>Questions during the beta</Text><Body>Open Settings, then Send feedback. You can review your notes before sending them to HunterOS. The full privacy policy below explains retention, service providers and account deletion. Verified deletion requests have a 30-day completion target; a minimal request record may remain for up to 90 days.</Body></Card>
 <AccountDataLinks/>
 </Page>;
}
