import {test,expect,type BrowserContext,type Page} from '@playwright/test';
const USER='11111111-1111-4111-8111-111111111111',OTHER='22222222-2222-4222-8222-222222222222',service='https://hunteros-test.invalid';
const source='https://www.mysteryranch.com/pop-up-30-pack';
function signed(id=USER){const exp=Math.floor(Date.now()/1000)+86400;return {access_token:[Buffer.from('{"alg":"HS256","typ":"JWT"}').toString('base64url'),Buffer.from(JSON.stringify({sub:id,exp,role:'authenticated'})).toString('base64url'),'synthetic-signature'].join('.'),refresh_token:'synthetic-only',token_type:'bearer',expires_in:86400,expires_at:exp,user:{id,email:'fixture@example.invalid',aud:'authenticated',role:'authenticated',email_confirmed_at:'2026-01-01T00:00:00Z',created_at:'2026-01-01T00:00:00Z',app_metadata:{},user_metadata:{}}};}
function imported(selected=false,currency='USD'){return {id:'import-preview',name:'Pop Up 30',brand:'Mystery Ranch',model:'',variant:selected?'Foliage S':'',category:'Pack system',kind:'Community product',weightGrams:2200,weightLabel:'2.2 kg (manufacturer reference)',weightCheckedAt:'2026-10-03',priceUSD:selected&&currency==='USD'?425:null,priceCheckedAt:selected?'2026-10-03':'',sourceURL:selected?source+'?variant=1':source,purchaseURL:source,checkedAt:'2026-10-03',note:'Manufacturer reference',tags:['community'],carry:'packed',photo:null,reviewStatus:'community',imported:{sku:selected?'FOL-S':'',price:selected?425:null,currency:selected?currency:'',weightValue:2.2,weightUnit:'kg',sourceCategory:'',attribution:'Imported from mysteryranch.com. Manufacturer reference.',missing:selected?['model','category','image']:['model','SKU','category','price','currency','image'],variants:[{key:'variant-0',label:'Foliage S'},{key:'variant-1',label:'Foliage M'}],selectedVariant:selected?'variant-0':''}};}
async function fixture(context:BrowserContext,options:{signed?:boolean;currency?:string;blockedImport?:boolean;food?:boolean;unknownMaker?:boolean}={}){
 const f={imports:[] as any[],blocked:false,canMessage:true,inboxError:false,hold:null as Promise<void>|null,started:null as (()=>void)|null,authHold:null as Promise<void>|null,authStarted:null as (()=>void)|null,unexpected:[] as string[]};
 if(options.signed!==false)await context.addInitScript(({value})=>{if(!localStorage.getItem('fixture-initialized')){localStorage.setItem('sb-hunteros-test-auth-token',JSON.stringify(value));localStorage.setItem('fixture-initialized','1');}},{value:signed()});
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin==='http://127.0.0.1:4176')return route.continue();if(url.origin!==service)return route.abort('blockedbyclient');const reply=(data:unknown,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});const body=route.request().postDataJSON()||{};const token=route.request().headers().authorization||'';let user=USER;try{user=JSON.parse(Buffer.from(token.split('.')[1],'base64url').toString()).sub;}catch{/* Anonymous synthetic request. */}
 if(url.pathname==='/auth/v1/token'){if(f.authHold){f.authStarted?.();await f.authHold;}return reply(signed(body.email==='other@example.invalid'?OTHER:USER));}if(url.pathname==='/auth/v1/user')return reply(signed(user).user);if(url.pathname==='/auth/v1/logout')return route.fulfill({status:204});
 if(url.pathname.endsWith('/hunteros_social_snapshot'))return reply({profile:{user_id:user,user_code:'12345678',name:'Fixture',friend_code:'legacy'},friends:[],groups:[],blocked:[],posts:[],signals:[]});
 if(url.pathname.endsWith('/hunteros_message_inbox'))return f.inboxError?reply({message:'Synthetic inbox unavailable'},500):reply({conversations:user===USER&&!f.blocked?[{user_id:OTHER,user_code:'87654321',name:'Ash',last_message:'Private camp plan',last_at:'2026-10-03T12:00:00Z',unread_count:2,can_message:f.canMessage}]:[]});
 if(url.pathname==='/rest/v1/community_products')return reply([]);
 if(url.pathname.endsWith('/product-import')){f.imports.push(body);const result=imported(!!body.variantKey,options.currency||'USD');if(options.food){Object.assign(result,{name:'Trail Bar 12 Pack',brand:'Trail Brand',category:'Food & nutrition',carry:'consumable',sourceURL:'https://retailer.com/products/trail-bar',purchaseURL:'https://retailer.com/products/trail-bar',weightGrams:600,weightLabel:'600 g net'});Object.assign(result.imported,{sku:body.variantKey?'BAR12':'',weightValue:600,weightUnit:'g',sourceCategory:'Food',variants:[{key:'variant-0',label:'12 Pack'}],selectedVariant:body.variantKey?'variant-0':'',facts:{manufacturer:'Maker Inc',seller:'Retail Store',parentCompany:'',identityEvidence:'page-stated',weightBasis:'net',packSize:'12 bars',servingBasis:'12 servings per package',servingCount:12,servingSize:'One bar (50 g)',nutrition:[{name:'calories',value:'180 kcal'}],ingredients:'Oats, nuts',allergens:'Contains nuts'}});}if(options.unknownMaker){result.brand='';(result.imported as any).facts.manufacturer='';(result.imported as any).facts.identityEvidence='unknown';}if(f.hold){const hold=f.hold;f.hold=null;f.started?.();await hold;}if(options.blockedImport)return reply({error:'This website blocked the lookup. Open the product page and enter its details manually.'},400);return reply({product:body.action==='publish'?{...result,id:'community-fixture'}:result});}
 f.unexpected.push(url.pathname);return reply({error:'Unexpected fixture request'},400);
 });return f;
}
async function importReview(page:any){await page.goto('/gear/edit');await page.getByLabel('Product page link',{exact:true}).fill(source);await page.getByRole('button',{name:'Import product details',exact:true}).click();await expect(page.getByText('Review product details',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Apply details to my private gear',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Choose: Foliage S',exact:true}).click();await expect(page.getByRole('button',{name:'Selected: Foliage S',exact:true})).toBeVisible();}

async function capture(page:Page,name:string){await page.evaluate(()=>{for(const el of document.querySelectorAll<HTMLElement>('div'))if(el.scrollHeight>el.clientHeight&&['auto','scroll'].includes(getComputedStyle(el).overflowY))el.scrollTop=0;globalThis.scrollTo(0,0);});await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/qa-${name}-${test.info().project.name}.png`,scale:'css'});}

async function captureAt(page:Page,name:string,text:string){await page.getByText(text,{exact:true}).scrollIntoViewIfNeeded();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/qa-${name}-${test.info().project.name}.png`,scale:'css'});}

test('review selected variant, edit privately, repeated save and reload preserve source details',async({page,context})=>{const f=await fixture(context);await importReview(page);await capture(page,'import-review');await captureAt(page,'import-variant-actions','Choose your exact variant');await page.getByRole('button',{name:'Apply details to my private gear',exact:true}).click();await expect(page.getByLabel('Item name',{exact:true})).toHaveValue('Pop Up 30');await expect(page.getByLabel('Weight per unit in grams (blank if unknown)',{exact:true})).toHaveValue('2200');await expect(page.getByLabel('Price per unit USD (blank if unknown)',{exact:true})).toHaveValue('425');await expect(page.getByLabel('Model (blank if unknown)',{exact:true})).toHaveValue('');await page.getByLabel('Item name',{exact:true}).fill('My edited pack');await page.getByLabel('Weight per unit in grams (blank if unknown)',{exact:true}).fill('2300');await page.getByRole('button',{name:'Save gear',exact:true}).evaluate((node:HTMLElement)=>{node.click();node.click();});await expect(page).toHaveURL(/\/locker$/);await page.reload();const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('hunteros.mobile.v1')!));expect(s.gear).toHaveLength(1);expect(s.gear[0].grams).toBe(2300);expect(s.gear[0].product.imported.sku).toBe('FOL-S');expect(s.gear[0].sourceURL).toContain('variant=1');expect(f.imports.map(x=>x.action)).toEqual(['preview','preview']);expect(f.unexpected).toEqual([]);await page.screenshot({path:`test-results/import-saved-${test.info().project.name}.png`,fullPage:true});});
test('currency remains a source reference and does not become USD',async({page,context})=>{await fixture(context,{currency:'CAD'});await importReview(page);await expect(page.getByText(/source price is retained in CAD/)).toBeVisible();await page.getByRole('button',{name:'Apply details to my private gear',exact:true}).click();await expect(page.getByLabel('Price per unit USD (blank if unknown)',{exact:true})).toHaveValue('');});
test('existing private values remain when applying and canonical duplicates are rejected',async({page,context})=>{await fixture(context);await importReview(page);await page.getByLabel('Item name',{exact:true}).fill('My existing name');await page.getByLabel('Weight per unit in grams (blank if unknown)',{exact:true}).fill('999');await page.getByRole('button',{name:'Apply details to my private gear',exact:true}).click();await expect(page.getByLabel('Item name',{exact:true})).toHaveValue('My existing name');await expect(page.getByLabel('Weight per unit in grams (blank if unknown)',{exact:true})).toHaveValue('999');await page.getByRole('button',{name:'Save gear',exact:true}).click();await expect(page).toHaveURL(/\/locker$/);await importReview(page);await page.getByRole('button',{name:'Apply details to my private gear',exact:true}).click();await page.getByRole('button',{name:'Save gear',exact:true}).click();await expect(page.getByText('This product is already here. Edit its quantity instead.',{exact:true})).toBeVisible();});
test('blocked lookup keeps a private source link and does not prevent manual saving',async({page,context})=>{await fixture(context,{blockedImport:true});await page.goto('/gear/edit');await page.getByLabel('Product page link',{exact:true}).fill(source);await page.getByRole('button',{name:'Import product details',exact:true}).click();await expect(page.getByText(/website blocked the lookup/)).toBeVisible();await page.getByLabel('Item name',{exact:true}).fill('Manual pack');await page.getByRole('button',{name:'Save gear',exact:true}).click();await expect(page).toHaveURL(/\/locker$/);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('hunteros.mobile.v1')!).gear[0].sourceURL)).toBe(source);});
test('sign-in interruption returns to the draft and stale responses cannot overwrite a changed URL',async({page,context})=>{const f=await fixture(context,{signed:false});await page.goto('/gear/edit');await page.getByLabel('Item name',{exact:true}).fill('Keep my draft');await page.getByLabel('Product page link',{exact:true}).fill(source);await page.getByRole('button',{name:'Sign in to import product details',exact:true}).click();await page.getByLabel('Email',{exact:true}).fill('fixture@example.invalid');await page.getByLabel('Password',{exact:true}).fill('synthetic-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/profile$/);await page.goBack();await expect(page.getByLabel('Item name',{exact:true})).toHaveValue('Keep my draft');let release!:()=>void;f.hold=new Promise(r=>release=r);const begun=new Promise<void>(r=>f.started=r);await page.getByRole('button',{name:'Import product details',exact:true}).evaluate((node:HTMLElement)=>{node.click();node.click();});await begun;await page.getByLabel('Product page link',{exact:true}).fill('https://www.mysteryranch.com/another-pack');release();await expect(page.getByText('Review product details',{exact:true})).toHaveCount(0);expect(f.imports).toHaveLength(1);});
test('Back during pending sign-in keeps the gear draft after auth completes',async({page,context})=>{
 const f=await fixture(context,{signed:false});let release!:()=>void;f.authHold=new Promise(r=>release=r);const begun=new Promise<void>(r=>f.authStarted=r);
 await page.goto('/gear/edit');await page.getByLabel('Item name',{exact:true}).fill('Keep my pending draft');await page.getByLabel('Product page link',{exact:true}).fill(source);await page.getByRole('button',{name:'Sign in to import product details',exact:true}).click();await page.getByLabel('Email',{exact:true}).fill('fixture@example.invalid');await page.getByLabel('Password',{exact:true}).fill('synthetic-only');await page.getByRole('button',{name:'Sign in',exact:true}).click();await begun;await page.goBack();await expect(page.getByLabel('Item name',{exact:true})).toHaveValue('Keep my pending draft');release();await expect(page.getByRole('button',{name:'Import product details',exact:true})).toBeVisible();await expect(page).toHaveURL(/\/gear\/edit$/);await expect(page.getByLabel('Item name',{exact:true})).toHaveValue('Keep my pending draft');await expect(page.getByLabel('Product page link',{exact:true})).toHaveValue(source);expect(f.imports).toHaveLength(0);
});
test('central inbox search unread filters and account switch clear private previews',async({page,context})=>{const f=await fixture(context);await page.goto('/');await expect(page.getByText('2 unread messages',{exact:true})).toBeVisible();await capture(page,'home');await page.getByRole('button',{name:'Open message inbox',exact:true}).click();await expect(page.getByText('Private camp plan',{exact:true})).toBeVisible();await capture(page,'inbox');await page.getByLabel('Search friends in messages',{exact:true}).fill('missing');await expect(page.getByText('No conversations match this filter.',{exact:true})).toBeVisible();await page.getByLabel('Search friends in messages',{exact:true}).fill('8765');await page.getByRole('button',{name:'Unread',exact:true}).click();await expect(page.getByText('Ash',{exact:true})).toBeVisible();const other=await context.newPage();await other.goto('/account');await other.getByRole('button',{name:'Sign out on this device',exact:true}).click();await expect(page.getByText('Private camp plan',{exact:true})).toHaveCount(0);await other.getByLabel('Email',{exact:true}).fill('other@example.invalid');await other.getByLabel('Password',{exact:true}).fill('synthetic-only');await other.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByText('Private camp plan',{exact:true})).toHaveCount(0);expect(f.unexpected).toEqual([]);});
test('food repeated taps add one consumable, essentials and first aid discovery work',async({page,context})=>{await fixture(context);await page.goto('/');await page.getByRole('button',{name:'Food & snack ideas',exact:true}).click();await capture(page,'food');await page.getByRole('button',{name:'Add Homemade trail mix',exact:true}).evaluate((node:HTMLElement)=>{node.click();node.click();});await expect(page.getByText(/Food idea added/)).toBeVisible();const s=await page.evaluate(()=>JSON.parse(localStorage.getItem('hunteros.mobile.v1')!));expect(s.gear).toHaveLength(1);expect(s.gear[0].carry).toBe('consumable');expect(s.gear[0].calories).toBeNull();await page.goBack();await page.getByRole('button',{name:'Find first-aid kits',exact:true}).click();await expect(page.getByRole('button',{name:'View Adventure Medical Kits Ultralight / Watertight .7',exact:true})).toBeVisible();await capture(page,'first-aid');await page.getByRole('button',{name:'View Adventure Medical Kits Ultralight / Watertight .7',exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`test-results/qa-first-aid-results-${test.info().project.name}.png`,scale:'css'});await page.goto('/offroad');await expect(page.getByText('10 SUGGESTED FOUR-WHEEL ESSENTIALS',{exact:true})).toBeVisible();await capture(page,'essentials');await captureAt(page,'essentials-list','10 SUGGESTED FOUR-WHEEL ESSENTIALS');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});


test('retailer food review keeps serving data separate, edits private facts and queues deduplicated source identities',async({page,context})=>{
 const f=await fixture(context,{food:true});await page.goto('/gear/edit');await page.getByLabel('Product page link',{exact:true}).fill('https://retailer.com/products/trail-bar');await page.getByRole('button',{name:'Import product details',exact:true}).click();await expect(page.getByText(/Seller \/ site: Retail Store/)).toBeVisible();await expect(page.getByText(/Pack size: 12 bars/)).toBeVisible();await page.getByRole('button',{name:'Choose: 12 Pack',exact:true}).click();await capture(page,'food-import-review');await page.getByText(/Pack size: 12 bars/).scrollIntoViewIfNeeded();await page.screenshot({path:`test-results/qa-food-source-facts-${test.info().project.name}.png`,scale:'css'});await page.getByRole('button',{name:'Apply details to my private gear',exact:true}).click();await expect(page.getByLabel('Calories per unit / package',{exact:true})).toHaveValue('');await expect(page.getByLabel('Source nutrition: calories',{exact:true})).toHaveValue('180 kcal');await page.getByLabel('Pack size (blank if unknown)',{exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:`test-results/qa-food-private-editor-${test.info().project.name}.png`,scale:'css'});await page.getByLabel('Manufacturer (blank if unknown)',{exact:true}).fill('Private maker correction');await page.getByLabel('Allergens (blank if unknown)',{exact:true}).fill('My checked label');await page.getByRole('button',{name:'Save gear',exact:true}).click();await expect(page).toHaveURL(/\/locker$/);await page.goto('/outreach');await expect(page.getByText('Maker Inc',{exact:true})).toBeVisible();await expect(page.getByText('Trail Brand',{exact:true})).toBeVisible();await expect(page.getByText('Retail Store',{exact:true})).toHaveCount(0);await expect(page.getByText('Private maker correction',{exact:true})).toHaveCount(0);const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('hunteros.mobile.v1')!));expect(state.outreachCandidates).toHaveLength(2);expect(state.gear[0].facts.allergens).toBe('My checked label');expect(state.gear[0].product.imported.facts.allergens).toBe('Contains nuts');expect(state.gear[0].calories).toBeNull();expect(f.imports.every(x=>Object.keys(x).sort().join(',')==='action,category,url,variantKey')).toBe(true);await page.reload();await expect(page.getByText('Maker Inc',{exact:true})).toBeVisible();await captureAt(page,'outreach-known-details','Maker Inc');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`test-results/outreach-${test.info().project.name}.png`,fullPage:true});
});


test('inbox read-only, blocked, service error and retry states never expose hidden conversations',async({page,context})=>{
 const f=await fixture(context);f.canMessage=false;await page.goto('/messages');await expect(page.getByText(/History only/)).toBeVisible();await capture(page,'inbox-read-only');f.blocked=true;await page.getByRole('button',{name:'Refresh messages',exact:true}).click();await expect(page.getByText('Private camp plan',{exact:true})).toHaveCount(0);await expect(page.getByText('Say hello to your crew.',{exact:true})).toBeVisible();await capture(page,'inbox-blocked');f.inboxError=true;await page.getByRole('button',{name:'Refresh messages',exact:true}).click();await expect(page.getByRole('button',{name:'Try messages again',exact:true})).toBeVisible();await expect(page.getByText('Private camp plan',{exact:true})).toHaveCount(0);f.inboxError=false;f.blocked=false;await page.getByRole('button',{name:'Try messages again',exact:true}).click();await expect(page.getByText('Private camp plan',{exact:true})).toBeVisible();expect(f.unexpected).toEqual([]);
});
test('signed-out inbox stays empty and food additions target only the chosen trip and loadout',async({page,context})=>{
 await fixture(context,{signed:false});await context.addInitScript(()=>localStorage.setItem('hunteros.mobile.v1',JSON.stringify({schema:'hunteros.mobile',version:2,gear:[],favorites:[],scannedProducts:[],loadouts:[{id:'qa-loadout',name:'QA loadout',activity:'Camping',style:'Base Camp',notes:'',items:[]}],trips:[{id:'qa-trip',name:'QA trip',type:'Hiking',region:'',area:'',date:'',days:2,people:1,style:'Day Hike',species:'',low:30,high:70,notes:'',items:[]}]})));
 await page.goto('/messages');await expect(page.getByText('Sign in to message your HunterOS friends.',{exact:true})).toBeVisible();await expect(page.getByText('Private camp plan',{exact:true})).toHaveCount(0);await capture(page,'inbox-signed-out');await page.goto('/food');await page.getByRole('button',{name:'Trip',exact:true}).click();await page.getByRole('button',{name:'Choose trip: QA trip',exact:true}).click();await page.getByRole('button',{name:'Add Homemade trail mix',exact:true}).click();await expect(page.getByText(/Food idea added/)).toBeVisible();await page.getByRole('button',{name:'Loadout',exact:true}).click();await page.getByRole('button',{name:'Choose loadout: QA loadout',exact:true}).click();await page.getByRole('button',{name:'Add Homemade trail mix',exact:true}).click();await expect(page.getByText(/Food idea added/)).toBeVisible();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('hunteros.mobile.v1')!));expect(state.gear).toHaveLength(0);expect(state.trips[0].items).toHaveLength(1);expect(state.loadouts[0].items).toHaveLength(1);expect(state.trips[0].items[0].grams).toBeNull();expect(state.loadouts[0].items[0].calories).toBeNull();expect(state.trips[0].items[0].owned).toBe(false);
});
test('unknown maker candidate retains the retailer source for private review',async({page,context})=>{
 await fixture(context,{food:true,unknownMaker:true});await page.goto('/gear/edit');await page.getByLabel('Product page link',{exact:true}).fill('https://retailer.com/products/trail-bar');await page.getByRole('button',{name:'Import product details',exact:true}).click();await expect(page.getByText(/Manufacturer: Unknown - needs review/)).toBeVisible();await page.getByRole('button',{name:'Choose: 12 Pack',exact:true}).click();await page.getByRole('button',{name:'Apply details to my private gear',exact:true}).click();await page.getByRole('button',{name:'Save gear',exact:true}).click();await expect(page).toHaveURL(/\/locker$/);await page.goto('/outreach');await expect(page.getByText('Maker unknown',{exact:true})).toBeVisible();await expect(page.getByText('Maker unknown - needs review',{exact:true})).toBeVisible();await capture(page,'outreach-unknown');const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('hunteros.mobile.v1')!));expect(state.outreachCandidates).toHaveLength(1);expect(state.outreachCandidates[0].sources[0].url).toBe('https://retailer.com/products/trail-bar');
});

test('privacy describes import review and private candidate backups',async({page,context})=>{await fixture(context);await page.goto('/privacy');await expect(page.getByText(/Applying the preview and saving gear keeps your copy private/)).toBeVisible();await expect(page.getByText(/These candidates are included when you choose a file export or cloud backup/)).toBeVisible();await captureAt(page,'privacy-import','Product links and shared references');});
