import test from 'node:test';
import assert from 'node:assert/strict';
import {gzipSync} from 'node:zlib';
import {extractProduct,fetchManufacturer,manufacturerURL} from '../supabase/functions/product-import/source.ts';
import {pinnedPageRequest} from '../supabase/functions/product-import/network.ts';
import {emptyProductFacts,importIdentity} from '../src/product-import-data.ts';
import {queueProductCandidate,readCandidates} from '../src/outreach-candidates.ts';
import {fresh,fromProduct,validateWorkspace,importBackup} from '../src/domain.ts';
import {productKey} from '../src/shared-products.ts';
const url='https://outdoor-retailer.com/item?id=ABC',page=data=>'<script type="application/ld+json">'+JSON.stringify(data)+'</script>';
const food={'@type':'Product',name:'Energy Bar 12 Pack',brand:{name:'Trail Brand'},manufacturer:{name:'Maker Inc',parentOrganization:{name:'Explicit Parent'}},sku:'BAR12',category:'Food',weight:{value:999,unitCode:'GRM'},shippingWeight:{value:222,unitCode:'KGM'},additionalProperty:[{name:'Net Weight',value:600,unitCode:'GRM'},{name:'Pack Size',value:'12 bars'}],offers:{price:24,priceCurrency:'CAD',seller:{name:'Retail Store'}},nutrition:{servingSize:'One bar (50 g)',numberOfServings:12,calories:'180 kcal',proteinContent:'7 g'},ingredients:'Oats, nuts',allergens:'Contains nuts'};
const dns=async()=>['93.184.216.34'];
function socket(response,{step=4096,partialWrite=false}={}){const bytes=typeof response==='string'?new TextEncoder().encode(response):response;let at=0,closed=0,written='';return {get closed(){return closed},get written(){return written},read:async out=>{if(at>=bytes.length)return null;const n=Math.min(out.length,step,bytes.length-at);out.set(bytes.subarray(at,at+n));at+=n;return n},write:async part=>{const n=partialWrite?Math.min(17,part.length):part.length;written+=new TextDecoder().decode(part.subarray(0,n));return n},close(){closed++;}};}
const raw=(body,headers='Content-Type: text/html\r\n')=>'HTTP/1.1 200 OK\r\n'+headers+'\r\n'+body;

test('ordinary public retailers and HTTP work; query product identities and selectors are preserved',()=>{assert.equal(manufacturerURL('http://retailer.com/item?id=ABC&utm_source=test#x').href,'http://retailer.com/item?id=ABC');assert.notEqual(productKey(url),productKey(url.replace('ABC','DEF')));assert.notEqual(importIdentity({sourceURL:url}),importIdentity({sourceURL:url.replace('ABC','DEF')}));for(const path of ['/login','/signin','/account','/cart','/checkout'])assert.throws(()=>manufacturerURL('https://retailer.com'+path));for(const query of ['token=private','API_KEY=private','signature=private'])assert.throws(()=>manufacturerURL('https://retailer.com/item?'+query));});
test('food identities distinguish brand manufacturer seller and explicitly stated parent',()=>{const p=extractProduct(page(food),url);assert.equal(p.brand,'Trail Brand');assert.equal(p.facts.manufacturer,'Maker Inc');assert.equal(p.facts.seller,'Retail Store');assert.equal(p.facts.parentCompany,'Explicit Parent');assert.equal(p.facts.identityEvidence,'page-stated');const unknown=extractProduct(page({'@type':'Product',name:'Food',offers:{seller:{name:'Retailer'}}}),url);assert.equal(unknown.brand,'');assert.equal(unknown.facts.manufacturer,'');assert.equal(unknown.facts.parentCompany,'');assert.equal(unknown.facts.seller,'Retailer');assert.equal(unknown.facts.identityEvidence,'unknown');});
test('net product weight and serving data never use shipping weight or infer calories per pack',()=>{const p=extractProduct(page(food),url);assert.equal(p.weightGrams,600);assert.equal(p.facts.weightBasis,'net');assert.equal(p.facts.servingSize,'One bar (50 g)');assert.equal(p.facts.packSize,'12 bars');assert.equal(p.facts.servingCount,12);assert.deepEqual(p.facts.nutrition,[{name:'calories',value:'180 kcal'},{name:'proteinContent',value:'7 g'}]);assert.equal(p.facts.ingredients,'Oats, nuts');const noWeight=extractProduct(page({...food,weight:undefined,additionalProperty:[],nutrition:{calories:'180 kcal'}}),url);assert.equal(noWeight.weightGrams,null);assert.equal(noWeight.facts.weightBasis,'unknown');assert.equal(noWeight.facts.servingCount,null);});
test('explicit labeled food facts are quoted; approximate container counts and serving grams are not pack totals',()=>{const h=page({'@type':'Product',name:'Chocolate 10 Pack',brand:'Chocolate Brand'})+'<h2>Ingredients</h2><p>Chocolate, almonds.</p><p>Contains almonds. May contain milk.</p><h2>Nutrition Facts</h2><p>About 3.5 servings per container<br>Serving size 7 pieces (29g)</p><p>Calories per serving: 160<br>Total Fat 11g, 14%<br>Protein 2g</p><h2>Reviews</h2><p>Protein 999g</p>';const p=extractProduct(h,url);assert.equal(p.facts.ingredients,'Chocolate, almonds.');assert.equal(p.facts.allergens,'Contains almonds. May contain milk.');assert.equal(p.facts.servingBasis,'About 3.5 servings per container');assert.equal(p.facts.servingCount,null);assert.equal(p.facts.servingSize,'7 pieces (29g)');assert.equal(p.weightGrams,null);assert.deepEqual(p.facts.nutrition,[{name:'calories',value:'160'},{name:'proteinContent',value:'2g'},{name:'fatContent',value:'11g, 14%'}]);});
test('retailer SKU radio options reveal flavor ambiguity without executing page scripts',()=>{const h=page({'@type':'Product',name:'Waffle',sku:'product-id',image:'https://cdn.retailer.com/coconut.jpg',weight:'30 g',offers:{'@type':'AggregateOffer',lowPrice:1.85,highPrice:1.85,priceCurrency:'USD'}})+'<label><input type="radio" name="sku" value="C"><span class="option-label">Coconut</span><img src="https://cdn.retailer.com/coconut.jpg"></label><label><input type="radio" name="sku" value="M"><span class="option-label">Maple</span><img src="https://cdn.retailer.com/maple.jpg"></label><script>throw Error("never execute")</script>';const initial=extractProduct(h,url);assert.equal(initial.variants.length,2);assert.equal(initial.sku,'');assert.equal(initial.price,null);assert.equal(initial.imageURL,'');const selected=extractProduct(h,url,'variant-1');assert.equal(selected.sku,'M');assert.equal(selected.name,'Waffle - Maple');assert.equal(selected.price,1.85);assert.match(selected.imageURL,/maple/);assert.equal(selected.weightGrams,null);});
test('cross-site redirects validate DNS and public images with private DNS are suppressed',async()=>{let calls=0;const result=await fetchManufacturer(url,async()=>++calls===1?new Response(null,{status:302,headers:{location:'https://brand.com/products/bar'}}):new Response(page({...food,image:'https://images.brand.com/bar.jpg'}),{headers:{'content-type':'text/html'}}),async hostname=>hostname==='images.brand.com'?['10.0.0.1']:['93.184.216.34']);assert.equal(calls,2);assert.equal(result.sourceURL,'https://brand.com/products/bar');assert.equal(result.imageURL,'');assert.ok(result.missing.includes('image'));});
test('pinned request connects to validated IP with original TLS identity and sends no user credentials',async()=>{const s=socket(raw('<html>product</html>'),{step:7,partialWrite:true});let opened;const r=await pinnedPageRequest(new URL(url),['93.184.216.34'],new AbortController().signal,async(...args)=>{opened=args;return s});assert.deepEqual(opened,['93.184.216.34','outdoor-retailer.com',true]);assert.equal(await r.text(),'<html>product</html>');assert.match(s.written,/GET \/item\?id=ABC HTTP\/1\.1\r\nHost: outdoor-retailer.com\r\n/);assert.doesNotMatch(s.written,/authorization|cookie|secret/i);assert.equal(s.closed,1);});
test('HTTP socket requests use port policy without silently changing protocol',async()=>{const s=socket(raw('ok'));let opened;await pinnedPageRequest(new URL('http://retailer.com/product'),['93.184.216.34'],new AbortController().signal,async(...args)=>{opened=args;return s});assert.equal(opened[2],false);});
test('HTTP framing supports complete chunks and rejects truncation ambiguous headers and oversized headers',async()=>{let s=socket(raw('4\r\nbody\r\n0\r\n\r\n','Transfer-Encoding: chunked\r\n'));assert.equal(await (await pinnedPageRequest(new URL(url),['93.184.216.34'],new AbortController().signal,async()=>s)).text(),'body');for(const bytes of [raw('4\r\nbody\r\n','Transfer-Encoding: chunked\r\n'),raw('x','Content-Length: 2\r\n'),raw('x','Content-Length: 1\r\nContent-Length: 1\r\n'),raw('0\r\n\r\n','Transfer-Encoding: chunked\r\nContent-Length: 5\r\n'),raw('x','X-Filler: '+'x'.repeat(17000)+'\r\n')]){s=socket(bytes);await assert.rejects(pinnedPageRequest(new URL(url),['93.184.216.34'],new AbortController().signal,async()=>s));assert.equal(s.closed,1);}});
test('HTTP decompression is bounded independently of compressed input',async()=>{const header=new TextEncoder().encode('HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-Encoding: gzip\r\n\r\n');for(const length of [100,4000001]){const compressed=gzipSync('x'.repeat(length)),bytes=new Uint8Array(header.length+compressed.length);bytes.set(header);bytes.set(compressed,header.length);const s=socket(bytes);const result=pinnedPageRequest(new URL(url),['93.184.216.34'],new AbortController().signal,async()=>s);if(length>4000000)await assert.rejects(result,/too large/);else assert.equal((await (await result).text()).length,length);assert.equal(s.closed,1);}});
test('abort closes sockets, including an already canceled connection',async()=>{const controller=new AbortController();controller.abort();const s=socket(raw('ok'));await assert.rejects(pinnedPageRequest(new URL(url),['93.184.216.34'],controller.signal,async()=>s),/timed out/);assert.equal(s.closed,1);});
test('private outreach queue deduplicates source identities and never makes a retailer into a manufacturer',()=>{const p={name:'Bar',brand:'Trail Brand',sourceURL:url,checkedAt:'2026-10-03',imported:{facts:extractProduct(page(food),url).facts}};let queue=queueProductCandidate([],p);assert.equal(queue.length,2);assert.deepEqual(queue.map(c=>c.role),['manufacturer','brand']);assert.ok(!queue.some(c=>c.name==='Retail Store'));queue=queueProductCandidate(queue,{...p,sourceURL:url+'&utm_source=ad'});assert.equal(queue.length,2);assert.equal(queue[0].sources.length,1);queue=queueProductCandidate(queue,{...p,sourceURL:'https://brand.com/products/bar'});assert.equal(queue[0].sources.length,2);assert.equal(queue[0].status,'source-stated');const unknown=queueProductCandidate([],{...p,brand:'',imported:{facts:emptyProductFacts()}});assert.equal(unknown[0].status,'needs-review');assert.equal(unknown[0].role,'unresolved');assert.throws(()=>readCandidates([...queue,queue[0]]));});
test('HTTP source facts, private edits and private candidates survive backup without changing source records',()=>{const p={id:'private',name:'Bar',brand:'Trail Brand',model:'',variant:'12 pack',category:'Food & nutrition',kind:'Product',weightGrams:600,weightLabel:'600 g net',weightCheckedAt:'',priceUSD:null,priceCheckedAt:'',sourceURL:'http://retailer.com/products/bar',purchaseURL:'http://retailer.com/products/bar',checkedAt:'2026-10-03',note:'Source',tags:[],carry:'consumable',photo:null,reviewStatus:'community',imported:{facts:extractProduct(page(food),url).facts,sku:'BAR12',price:24,currency:'CAD',weightValue:600,weightUnit:'g',sourceCategory:'Food',attribution:'Source',missing:[],variants:[],selectedVariant:''}};const g=fromProduct(p,true);g.facts={...p.imported.facts,manufacturer:'Private correction'};g.calories=2000;const s={...fresh(),gear:[g],outreachCandidates:queueProductCandidate([],p)},restored=importBackup(JSON.parse(JSON.stringify(validateWorkspace(s))));assert.equal(restored.gear[0].product.sourceURL,p.sourceURL);assert.equal(restored.gear[0].facts.manufacturer,'Private correction');assert.equal(restored.gear[0].product.imported.facts.manufacturer,'Maker Inc');assert.equal(restored.gear[0].calories,2000);assert.equal(restored.outreachCandidates[0].name,'Maker Inc');});
