import { useMemo, useState } from 'react';
import { FlatList, Text, View, useWindowDimensions } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useCatalog } from '@/use-catalog';
import { CATEGORIES, filterProducts } from '@/domain';
import { useStore } from '@/store';
import { Button, C, Chips, Field, Label, ProductCard, s } from '@/ui';
export default function Catalog(){const {products:catalog,loading,error,refresh}=useCatalog(),router=useRouter(),brands=[...new Set(catalog.map(p=>p.brand))].sort();const {tripId}=useLocalSearchParams<{tripId?:string}>(),{state}=useStore();const [query,setQuery]=useState(''),[brand,setBrand]=useState('All brands'),[category,setCategory]=useState('All categories'),[mode,setMode]=useState('All gear'),[sort,setSort]=useState('Featured');const inset=useSafeAreaInsets(),{width}=useWindowDimensions(),cols=width>=720?2:1;
 const products=useMemo(()=>filterProducts(catalog,{query,brand:brand==='All brands'?undefined:brand,category:category==='All categories'?undefined:category,photosOnly:mode==='With photos',knownWeight:mode==='Known weight',favorites:mode==='Favorites'?state.favorites:null,sort:sort==='Lightest'?'weight':sort==='Lowest price'?'price':sort==='A–Z'?'name':'featured'}),[catalog,query,brand,category,mode,sort,state.favorites]);
 return <FlatList key={cols} style={{flex:1,backgroundColor:C.bg}} contentInsetAdjustmentBehavior="automatic" data={products} numColumns={cols} keyExtractor={p=>p.id} keyboardShouldPersistTaps="handled" initialNumToRender={6} maxToRenderPerBatch={6} windowSize={5} contentContainerStyle={{padding:16,paddingBottom:inset.bottom+24,maxWidth:1120,width:'100%',alignSelf:'center'}} columnWrapperStyle={cols>1?{gap:14}:undefined} renderItem={({item})=><View style={{flex:1,maxWidth:cols>1?'50%':'100%',marginBottom:14}}><ProductCard product={item} tripId={tripId}/></View>} ListHeaderComponent={<View style={{gap:12,paddingBottom:16}}><Label>REAL GEAR. YOUR SYSTEM.</Label><Text style={s.title}>Find your next piece.</Text><Text style={s.body}>{catalog.length} catalog configurations · {catalog.filter(p=>p.photo).length} photo references</Text><Button secondary title="Add a product for everyone" onPress={()=>router.push('/gear/edit')}/><Button secondary title={loading?'Refreshing shared products...':'Refresh shared products'} disabled={loading} onPress={()=>void refresh()}/>{error?<Text style={s.small}>{error}</Text>:null}<Field label="Search gear" value={query} onChangeText={setQuery} placeholder="Kifaru, rain pants, Maven, stove…" autoCapitalize="none" autoCorrect={false}/><Chips values={['All gear','With photos','Favorites','Known weight']} value={mode} onChange={setMode}/><Chips values={['All categories',...CATEGORIES]} value={category} onChange={setCategory}/><Chips values={['All brands',...brands]} value={brand} onChange={setBrand}/><Chips values={['Featured','A–Z','Lightest','Lowest price']} value={sort} onChange={setSort}/><View style={[s.row,{justifyContent:'space-between'}]}><Text selectable style={s.small}>{products.length} matches · prices are not live</Text><Button secondary title="Reset filters" onPress={()=>{setQuery('');setBrand('All brands');setCategory('All categories');setMode('All gear');setSort('Featured');}}/></View>{tripId?<Text style={{color:C.lime}}>Shopping for a trip · select a product to add it.</Text>:null}</View>} ListEmptyComponent={<View style={s.card}><Text style={s.h2}>Nothing here yet.</Text><Text style={s.body}>Try fewer filters or save a product to your favorites.</Text></View>}/>;
}
