import { useState } from 'react';
import { Link, useRouter } from 'expo-router';
import { Pressable, Text, View } from 'react-native';
import { useStore } from '@/store';
import { Button, Card, C, ErrorText, Label, Page, ProductCard, s } from '@/ui';
import { generateChecklist, totals, uid } from '@/domain';
import { catalog } from '@/catalog';
import type { Trip } from '@/types';
export default function Home(){const {state,commit,saving}=useStore(),router=useRouter(),[error,setError]=useState('');
 async function sample(){try{const t:Trip={id:uid(),name:'Colorado elk · sample',type:'Hunting + Camping',region:'Colorado',area:'Set your trailhead',date:'',days:5,people:1,style:'Backcountry',species:'Elk',low:25,high:60,notes:'Sample assumptions only; not current conditions.',items:generateChecklist('Hunting + Camping','Backcountry',5)};await commit(s=>({...s,trips:[t,...s.trips]}));router.push({pathname:'/trip/[id]',params:{id:t.id}});}catch(e){setError(String(e));}}
 return <Page><View style={{paddingVertical:12,gap:10}}><Label>PLAN LESS. GET OUT THERE.</Label><Text style={[s.title,{fontSize:36}]}>{'Your next trip,\nall in one place.'}</Text><Text style={s.body}>Hunt. Camp. Pack what matters.</Text></View><Button title="Build a trip" onPress={()=>router.push('/trip/new')}/><Button secondary title="Try a sample hunt" onPress={()=>void sample()} disabled={saving}/><ErrorText message={error}/><View style={[s.row,{justifyContent:'space-between'}]}><Text style={s.h2}>Your trips</Text><Text style={s.small}>{state.gear.length} items in locker</Text></View>{!state.trips.length?<Card><Label>START WITH THE TRIP</Label><Text style={s.body}>Create a hunt, camping trip or backpacking plan. Your equipment stays saved on this device.</Text></Card>:state.trips.map(t=>{const x=totals(t.items);return <Link key={t.id} href={{pathname:'/trip/[id]',params:{id:t.id}}} asChild><Pressable style={s.card}><Label>{t.type}</Label><Text style={s.h2}>{t.name}</Text><Text style={s.body}>{t.region} · {t.days} days · {t.style}</Text><View style={{height:5,backgroundColor:C.line,borderRadius:8}}><View style={{height:5,width:`${x.progress}%`,backgroundColor:C.lime,borderRadius:8}}/></View><Text style={s.small}>{x.packed}/{t.items.length} lines packed · {(x.carried/453.59237).toFixed(1)} lb listed{x.unknownWeight?' · partial':''}</Text></Pressable></Link>})}<Text style={s.h2}>A closer look at your gear</Text>{catalog.filter(p=>p.photo).slice(0,3).map(p=><ProductCard key={p.id} product={p}/>)}<Text style={s.small}>Family beta · Trip planning with optional accounts and manual cloud backup.</Text></Page>;
}
