import { useState } from 'react';
import { Link, useLocalSearchParams, useRouter } from 'expo-router';
import { Text, View } from 'react-native';
import { useStore } from '@/store';
import { Button, Card, ErrorText, Field, Label, Page, s } from '@/ui';
import { uid, weight } from '@/domain';
import type { Gear } from '@/types';
export default function Locker(){const {tripId}=useLocalSearchParams<{tripId?:string}>(),{state,commit,saving}=useStore(),router=useRouter(),[search,setSearch]=useState(''),[message,setMessage]=useState('');
 async function useItem(g:Gear){try{await commit(s=>{const t=s.trips.find(t=>t.id===tripId);if(!t)throw Error('Choose a trip first.');if(t.items.some(i=>g.product?i.product?.id===g.product.id:i.name===g.name))throw Error('Already in this trip; edit its quantity instead.');t.items.push({...g,id:uid(),owned:true,packed:false});return s;});setMessage('Owned copy added to this trip.');}catch(e){setMessage(String(e));}}
 return <Page><Label>USE WHAT YOU OWN</Label><Text style={s.title}>Your gear locker.</Text><Text style={s.body}>Real equipment. Your measured weights. Reuse it on every trip.</Text><Button title="Scan barcode / enter SKU" onPress={()=>router.push('/gear/scan')}/><Button title="Add custom gear" onPress={()=>router.push('/gear/edit')}/><Button secondary title="Browse the catalog" onPress={()=>router.push('/catalog')}/>{tripId?<Link href={{pathname:'/trip/[id]',params:{id:tripId}}} style={{color:'#d4ef79',padding:12}}>Return to trip →</Link>:null}<Field label="Search your locker" value={search} onChangeText={setSearch} placeholder="Search owned equipment…"/><ErrorText message={message}/>{state.gear.filter(i=>i.name.toLowerCase().includes(search.toLowerCase())).map(g=><Card key={g.id}><Label>{g.category}</Label><Text style={s.h2}>{g.name}</Text><Text selectable style={s.body}>{g.quantity} × {weight(g.grams)}</Text><View style={s.row}><Button secondary title="Edit gear" onPress={()=>router.push({pathname:'/gear/edit',params:{id:g.id}})}/>{tripId?<Button title="Use in this trip" disabled={saving} onPress={()=>void useItem(g)}/>:null}</View></Card>)}{!state.gear.length?<Card><Text style={s.h2}>Start with your pack.</Text><Text style={s.body}>Add equipment manually or open a catalog product and choose “I own this.” Locker copies stay separate from trip copies.</Text></Card>:null}</Page>;
}
