import { useState } from 'react';
import { useRouter } from 'expo-router';
import { appVersion } from '@/feedback';
import { Text } from 'react-native';
import { useStore } from '@/store';
import { importBackup } from '@/domain';
import { exportFile, importFile } from '@/backup';
import { confirmAction } from '@/dialogs';
import { Button, Card, ErrorText, Label, Page, s } from '@/ui';
export default function Settings(){const router=useRouter(),{state,commit,saving}=useStore(),[message,setMessage]=useState('');
 async function backup(){try{await exportFile(JSON.stringify(state,null,2));setMessage('Backup prepared. Save a copy somewhere safe.');}catch(e){setMessage(String(e));}}
 async function restore(){try{const raw=await importFile();if(!raw)return;const next=importBackup(JSON.parse(raw));if(!await confirmAction('Replace this workspace?',`${next.trips.length} trips, ${next.loadouts.length} loadouts and ${next.gear.length} locker entries will replace the current data. Export a backup first to keep the current workspace.`))return;await commit(()=>next);setMessage('Backup imported.');}catch(e){setMessage('Import did not change your workspace: '+String(e));}}
 return <Page><Label>HUNTEROS / {appVersion} FAMILY BETA</Label><Text style={s.title}>Your workspace.</Text><Card><Text style={s.h2}>Make it better together.</Text><Text style={s.body}>Found a bug or have an idea? Share a quick report with the person who invited you.</Text><Button title="Send feedback" onPress={()=>router.push('/feedback')}/></Card><Card><Text style={s.h2}>Privacy & data</Text><Text style={s.body}>See what stays on your device, how product photos load, and what happens when you share a backup or feedback.</Text><Button secondary title="Privacy & data" onPress={()=>router.push('/privacy')}/></Card><Card><Text style={s.h2}>Account & cloud backup</Text><Text style={s.body}>Sign in to save an optional cloud copy. Upload and restore are manual, so offline changes are kept until you choose what to replace.</Text><Button title="Account & cloud backup" onPress={()=>router.push('/account')}/></Card><Card><Text style={s.h2}>Backup & transfer</Text><Text style={s.body}>{state.trips.length} trips · {state.loadouts.length} loadouts · {state.gear.length} locker items · {state.favorites.length} favorites</Text><Button title="Export backup" onPress={()=>void backup()} disabled={saving}/><Button secondary title="Import backup" onPress={()=>void restore()} disabled={saving}/><Text style={s.small}>Mobile backups preserve trips, loadouts, gear, source references, favorites and scan history. Browser v0.2–v1.0 backups import lists, notes, ownership and weights; old catalog links, weather badges and unsupported fields are not transferred.</Text></Card><ErrorText message={message}/><Card><Text style={s.h2}>Offline: what works</Text><Text style={s.body}>Trips, loadouts, gear and packing changes are saved on this device. The installable app includes its catalog and does not need Expo Go or a running computer. Each family member has a separate workspace.</Text><Text style={s.body}>Product photos and shopping pages need internet. Before a trip, test opening the app and your packing list in airplane mode. Keep a backup of important plans.</Text></Card><Card><Text style={s.h2}>Photos & product data</Text><Text style={s.body}>Product photos are loaded from their source sites and may be unavailable offline. Check the linked product page for the exact size and configuration.</Text><Text style={s.body}>The legacy catalog is preserved but not claimed to be newly verified. Only individually dated weight checks are marked source-checked. Prices are dated references, never live offers.</Text></Card><Card><Text style={s.h2}>Optional online features</Text><Text style={s.body}>You can use HunterOS without an account. Cloud backup sends a copy of your workspace to Supabase only when you choose to upload it. It does not merge changes across phones automatically. Barcode lookup can send the scanned code to Open Food Facts. Weather and maps are not connected.</Text></Card></Page>;
}
