import { useState } from 'react';
import { useRouter } from 'expo-router';
import { Text } from 'react-native';
import { useStore } from '@/store';
import { importBackup } from '@/domain';
import { exportFile, importFile } from '@/backup';
import { confirmAction } from '@/dialogs';
import { Button, Card, ErrorText, Label, Page, s } from '@/ui';
export default function Settings(){const router=useRouter(),{state,commit,saving}=useStore(),[message,setMessage]=useState('');
 async function backup(){try{await exportFile(JSON.stringify(state,null,2));setMessage('Backup prepared. Save a copy somewhere safe.');}catch(e){setMessage(String(e));}}
 async function restore(){try{const raw=await importFile();if(!raw)return;const next=importBackup(JSON.parse(raw));if(!await confirmAction('Replace this workspace?',`${next.trips.length} trips and ${next.gear.length} locker entries will replace the current data. Export a backup first to keep the current workspace.`))return;await commit(()=>next);setMessage('Backup imported.');}catch(e){setMessage('Import did not change your workspace: '+String(e));}}
 return <Page><Label>HUNTEROS MOBILE / 0.1.0</Label><Text style={s.title}>Your workspace.</Text><Card><Text style={s.h2}>HunterOS account & cloud</Text><Text style={s.body}>Keep SQLite for offline use and sync an account copy to the HunterOS cloud backend.</Text><Button title="Account & cloud sync" onPress={()=>router.push('/account')}/></Card><Card><Text style={s.h2}>Backup & transfer</Text><Text style={s.body}>{state.trips.length} trips · {state.gear.length} locker items · {state.favorites.length} favorites</Text><Button title="Export backup" onPress={()=>void backup()} disabled={saving}/><Button secondary title="Import backup" onPress={()=>void restore()} disabled={saving}/><Text style={s.small}>Mobile backups preserve trips, gear, source references and favorites. Browser v0.2–v1.0 backups import lists, notes, ownership and weights; old catalog links, weather badges and unsupported fields are not transferred.</Text></Card><ErrorText message={message}/><Card><Text style={s.h2}>Offline: what works</Text><Text style={s.body}>The native app saves trips, gear and packing changes to SQLite on this device. The catalog is packaged with the JavaScript bundle. Web preview storage is separate and browser-local.</Text><Text style={s.body}>Manufacturer photos, shopping links and Expo Go’s development bundle can require a connection. This is not yet a certified, standalone cold-start offline build. Never use it as your only navigation or emergency resource.</Text></Card><Card><Text style={s.h2}>Photos & product data</Text><Text style={s.body}>Source-linked product photos are prototype references, not generated look-alikes. Sizes, configurations and image licensing must be reviewed before a commercial launch. Photos are loaded directly, with disk caching disabled for these reference images.</Text><Text style={s.body}>The legacy catalog is preserved but not claimed to be newly verified. Only individually dated weight checks are marked source-checked. Prices are dated references, never live offers.</Text></Card><Card><Text style={s.h2}>Still coming</Text><Text style={s.body}>Cloud accounts are now implemented once a Supabase project is configured. No affiliate commissions, payments, live weather or onX API yet. Trip conditions are user assumptions. No locations or trip data are sent to a backend; loading remote photos sends ordinary image requests to their hosts.</Text></Card></Page>;
}
