import { useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Text } from 'react-native';
import { Button, C, Chips, ErrorText, Field, Label, Page, s } from '@/ui';
import { useStore } from '@/store';
import { CATEGORIES, newGear, validateGear } from '@/domain';
import { confirmAction } from '@/dialogs';
import type { Carry, Category } from '@/types';
export default function GearEditor(){const {id,tripId}=useLocalSearchParams<{id?:string;tripId?:string}>(),{state,commit,saving}=useStore(),router=useRouter();const original=(tripId?state.trips.find(t=>t.id===tripId)?.items:state.gear)?.find(i=>i.id===id);const base=original||newGear();
 const [name,setName]=useState(base.name),[category,setCategory]=useState<Category>(base.category),[grams,setGrams]=useState(base.grams===null?'':String(base.grams)),[price,setPrice]=useState(base.price===null?'':String(base.price)),[calories,setCalories]=useState(base.calories===null?'':String(base.calories)),[quantity,setQuantity]=useState(String(base.quantity)),[carry,setCarry]=useState<Carry>(base.carry),[owned,setOwned]=useState(!tripId||base.owned),[packed,setPacked]=useState(base.packed),[note,setNote]=useState(base.note),[error,setError]=useState('');
 async function save(){try{const value=validateGear({...base,id:id||base.id,name:name.trim(),category,grams:grams.trim()===''?null:Number(grams),price:price.trim()===''?null:Number(price),calories:calories.trim()===''?null:Number(calories),quantity:Number(quantity),carry,owned,packed,note},!tripId);await commit(s=>{const a=tripId?s.trips.find(t=>t.id===tripId)?.items:s.gear;if(!a)throw Error('Trip no longer exists.');const at=a.findIndex(g=>g.id===id);if(id&&at<0)throw Error('Gear no longer exists.');if(at>=0)a[at]=value;else a.push(value);return s;});router.back();}catch(e){setError(e instanceof Error?e.message:String(e));}}
 async function remove(){if(!await confirmAction('Remove this item?','Other trip and locker copies will not be removed.'))return;try{await commit(s=>{if(tripId){const t=s.trips.find(t=>t.id===tripId);if(t)t.items=t.items.filter(i=>i.id!==id);}else s.gear=s.gear.filter(i=>i.id!==id);return s;});router.back();}catch(e){setError(String(e));}}
 if(id&&!original)return <Page><Text style={s.h2}>Gear not found.</Text><Button title="Back" onPress={()=>router.back()}/></Page>;
 return <Page><Label>{tripId?'TRIP EQUIPMENT':'OWNED EQUIPMENT'}</Label><Field label="Item name" value={name} onChangeText={setName} placeholder="My pack, food pouch or rain jacket" maxLength={200}/><Text style={s.small}>Category</Text><Chips values={CATEGORIES} value={category} onChange={v=>setCategory(v as Category)}/><Field label="Weight per unit in grams (blank if unknown)" value={grams} onChangeText={setGrams} keyboardType="decimal-pad"/><Text style={s.small}>1 oz = 28.3495 g · 1 lb = 453.59237 g. Weigh your complete configuration, including accessories.</Text><Field label="Quantity" value={quantity} onChangeText={setQuantity} keyboardType="number-pad"/><Field label="Price per unit USD (blank if unknown)" value={price} onChangeText={setPrice} keyboardType="decimal-pad"/>{category==='Food & nutrition'?<Field label="Calories per unit / package" value={calories} onChangeText={setCalories} keyboardType="number-pad"/>:null}<Chips values={['In pack','Worn','Consumable']} value={carry==='packed'?'In pack':carry==='worn'?'Worn':'Consumable'} onChange={v=>setCarry(v==='In pack'?'packed':v==='Worn'?'worn':'consumable')}/>{tripId?<><Button secondary title={owned?'Owned ✓':'Not owned'} onPress={()=>setOwned(!owned)}/><Button secondary title={packed?'Packed ✓':'Not packed'} onPress={()=>setPacked(!packed)}/></>:null}<Field label="Configuration / notes" value={note} onChangeText={setNote} multiline maxLength={2000}/><Text style={s.small}>Unknown values stay blank and are excluded from partial totals. Checking “Packed” does not change planned weight.</Text><ErrorText message={error}/><Button title={saving?'Saving…':'Save gear'} onPress={()=>void save()} disabled={saving}/>{id?<Button secondary title="Remove item" onPress={()=>void remove()} disabled={saving}/>:null}</Page>;
}
