import { useEffect, useRef, useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Linking, Text } from 'react-native';
import { Button, Card, Chips, ErrorText, Field, Label, Page, ProductPhoto, s } from '@/ui';
import { useStore } from '@/store';
import { CATEGORIES, newGear, uid, validateGear } from '@/domain';
import { confirmAction } from '@/dialogs';
import { manufacturerProduct } from '@/community';
import { gearProduct, exactProduct } from '@/shared-products';
import { rememberSharedProduct, useCatalog } from '@/use-catalog';
import type { Carry, Category, Product } from '@/types';
export default function GearEditor(){
 const {id,tripId,loadoutId}=useLocalSearchParams<{id?:string;tripId?:string;loadoutId?:string}>(),{state,commit,saving}=useStore(),router=useRouter();
 const original=(loadoutId?state.loadouts.find(l=>l.id===loadoutId)?.items:tripId?state.trips.find(t=>t.id===tripId)?.items:state.gear)?.find(i=>i.id===id);
 const [base]=useState(()=>original||newGear());const {products}=useCatalog();
 const [name,setName]=useState(base.name),[category,setCategory]=useState<Category>(base.category),[grams,setGrams]=useState(base.grams===null?'':String(base.grams)),[price,setPrice]=useState(base.price===null?'':String(base.price)),[calories,setCalories]=useState(base.calories===null?'':String(base.calories)),[quantity,setQuantity]=useState(String(base.quantity)),[carry,setCarry]=useState<Carry>(base.carry),[owned,setOwned]=useState((!tripId&&!loadoutId)||base.owned),[packed,setPacked]=useState(base.packed),[note,setNote]=useState(base.note),[error,setError]=useState('');
 const [attached,setAttached]=useState<Product|null>(base.product),[url,setURL]=useState(base.product?.photo?.sourceURL||base.product?.sourceURL||''),[preview,setPreview]=useState<Product|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const request=useRef(0);useEffect(()=>()=>{request.current++;},[]);
 const matched=attached||exactProduct(name,products);
 const shown=matched?gearProduct({...base,product:matched},products):null;
 function changeURL(value:string){request.current++;setURL(value);setPreview(null);setBusy(false);setMessage('');setError('');}
 async function findPhoto(){const token=++request.current;setBusy(true);setError('');setMessage('');setPreview(null);try{const p=await manufacturerProduct(url,category,'preview');if(token===request.current)setPreview(p);}catch(e){if(token===request.current)setError(e instanceof Error?e.message:String(e));}finally{if(token===request.current)setBusy(false);}}
 async function share(){if(!preview)return;const token=++request.current;setBusy(true);setError('');try{const p=await manufacturerProduct(preview.sourceURL,category,'publish');if(token!==request.current)return;rememberSharedProduct(p);setAttached(p);setPreview(null);setName(current=>current.trim()?current:p.name);setMessage('Product and picture added to the shared catalog. Save below to keep it in your gear.');}catch(e){if(token===request.current)setError(e instanceof Error?e.message:String(e));}finally{if(token===request.current)setBusy(false);}}
 function useLocally(){if(!preview)return;setAttached({...preview,id:'local-product-'+uid()});setName(current=>current.trim()?current:preview.name);setPreview(null);setMessage('Picture attached to your gear only.');}
 async function save(){try{const value=validateGear({...base,id:id||base.id,product:shown,name:name.trim(),category,grams:grams.trim()===''?null:Number(grams),price:price.trim()===''?null:Number(price),calories:calories.trim()===''?null:Number(calories),quantity:Number(quantity),carry,owned,packed:loadoutId?false:packed,note},!tripId&&!loadoutId);await commit(s=>{const a=loadoutId?s.loadouts.find(l=>l.id===loadoutId)?.items:tripId?s.trips.find(t=>t.id===tripId)?.items:s.gear;if(!a)throw Error('This trip or loadout no longer exists.');const at=a.findIndex(g=>g.id===id);if(id&&at<0)throw Error('Gear no longer exists.');if(at>=0)a[at]=value;else a.push(value);return s;});if(router.canGoBack())router.back();else if(loadoutId)router.replace({pathname:'/loadout/[id]',params:{id:loadoutId}});else if(tripId)router.replace({pathname:'/trip/[id]',params:{id:tripId}});else router.replace('/locker');}catch(e){setError(e instanceof Error?e.message:String(e));}}
 async function remove(){if(!await confirmAction('Remove this item?','Other trip and locker copies, and the shared catalog product, will not be removed.'))return;try{await commit(s=>{if(loadoutId){const l=s.loadouts.find(l=>l.id===loadoutId);if(l)l.items=l.items.filter(i=>i.id!==id);}else if(tripId){const t=s.trips.find(t=>t.id===tripId);if(t)t.items=t.items.filter(i=>i.id!==id);}else s.gear=s.gear.filter(i=>i.id!==id);return s;});router.back();}catch(e){setError(String(e));}}
 if(id&&!original)return <Page><Text style={s.h2}>Gear not found.</Text><Button title="Back to locker" onPress={()=>router.replace('/locker')}/></Page>;
 return <Page><Label>{loadoutId?'LOADOUT EQUIPMENT':tripId?'TRIP EQUIPMENT':'OWNED EQUIPMENT'}</Label><Field label="Item name" value={name} onChangeText={setName} placeholder="My pack, food pouch or rain jacket" maxLength={200}/>{shown?.photo?<ProductPhoto product={shown} height={210}/>:null}
 <Card><Label>MANUFACTURER PICTURE</Label><Text style={s.body}>Paste the product page to find its picture. Share the product so everyone can find it in HunterOS. Your gear notes, measured weight, quantity and price paid stay private.</Text><Field label="Manufacturer product link" value={url} onChangeText={changeURL} placeholder="https://manufacturer.com/products/your-product" autoCapitalize="none" autoCorrect={false} keyboardType="url" maxLength={2048} editable={!busy}/><Button secondary title={busy?'Checking manufacturer…':'Find manufacturer picture'} onPress={()=>void findPhoto()} disabled={busy||!url.trim()}/>
 {preview?<><ProductPhoto product={preview} height={230}/><Text style={s.h2}>{preview.name}</Text><Text style={s.small}>Confirm this is your product. The picture may show a different size or accessories. Only product information from the page will be shared.</Text><Button secondary title="Open manufacturer page ↗" onPress={()=>void Linking.openURL(preview.sourceURL).catch(()=>setError('Could not open the manufacturer page.'))}/><Button title="Use picture and share product with everyone" onPress={()=>void share()} disabled={busy}/><Button secondary title="Keep this product private" onPress={useLocally} disabled={busy}/></>:null}{message?<Text accessibilityRole="alert" style={s.body}>{message}</Text>:null}</Card>
 <Text style={s.small}>Category</Text><Chips values={CATEGORIES} value={category} onChange={v=>{if(!busy)setCategory(v as Category);}}/><Field label="Weight per unit in grams (blank if unknown)" value={grams} onChangeText={setGrams} keyboardType="decimal-pad"/><Text style={s.small}>1 oz = 28.3495 g · 1 lb = 453.59237 g. Weigh your complete configuration, including accessories.</Text><Field label="Quantity" value={quantity} onChangeText={setQuantity} keyboardType="number-pad"/><Field label="Price per unit USD (blank if unknown)" value={price} onChangeText={setPrice} keyboardType="decimal-pad"/>{category==='Food & nutrition'?<Field label="Calories per unit / package" value={calories} onChangeText={setCalories} keyboardType="number-pad"/>:null}<Chips values={['In pack','Worn','Consumable']} value={carry==='packed'?'In pack':carry==='worn'?'Worn':'Consumable'} onChange={v=>setCarry(v==='In pack'?'packed':v==='Worn'?'worn':'consumable')}/>{tripId||loadoutId?<><Button secondary title={owned?'Owned ✓':'Not owned'} onPress={()=>setOwned(!owned)}/>{!loadoutId?<Button secondary title={packed?'Packed ✓':'Not packed'} onPress={()=>setPacked(!packed)}/>:null}</>:null}<Field label="Configuration / notes" value={note} onChangeText={setNote} multiline maxLength={2000}/><Text style={s.small}>Unknown values stay blank and are excluded from partial totals. Checking “Packed” does not change planned weight.</Text><ErrorText message={error}/><Button title={saving?'Saving…':'Save gear'} onPress={()=>void save()} disabled={saving||busy||!!preview}/>{id?<Button secondary title="Remove item" onPress={()=>void remove()} disabled={saving||busy}/>:null}</Page>;
}
