import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from 'react-native';
import { Image } from 'expo-image';
import { Link } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import type { Product } from './types';
import { money, weight } from './domain';
export const C={bg:'#0c100d',panel:'#172017',line:'#30402e',ink:'#f0f4ed',muted:'#a8b6a2',lime:'#d4ef79',warn:'#f0c485'};
export const s=StyleSheet.create({page:{padding:18,gap:16,maxWidth:960,width:'100%',alignSelf:'center'},row:{flexDirection:'row',alignItems:'center',gap:10,flexWrap:'wrap'},card:{padding:18,gap:10,borderRadius:18,borderCurve:'continuous',backgroundColor:C.panel,borderWidth:1,borderColor:C.line},title:{fontSize:30,fontWeight:'800',letterSpacing:-.9,color:C.ink},h2:{fontSize:21,fontWeight:'700',color:C.ink},body:{fontSize:14,lineHeight:21,color:C.muted},label:{fontSize:10,fontWeight:'800',letterSpacing:1.6,color:C.lime},button:{minHeight:46,borderRadius:12,paddingVertical:12,paddingHorizontal:17,backgroundColor:C.lime,alignItems:'center',justifyContent:'center'},buttonText:{fontWeight:'800',color:C.bg,fontSize:14},input:{minHeight:48,borderWidth:1,borderColor:'#53644d',backgroundColor:'#101711',borderRadius:12,padding:13,fontSize:16,color:C.ink},chip:{minHeight:44,paddingVertical:11,paddingHorizontal:15,borderRadius:30,borderWidth:1,borderColor:C.line,backgroundColor:C.panel},small:{fontSize:12,color:C.muted,lineHeight:18},stat:{fontVariant:['tabular-nums'],fontSize:25,fontWeight:'800',color:C.ink}});
export function Page({children}:{children:React.ReactNode}){const inset=useSafeAreaInsets();return <ScrollView style={{flex:1,backgroundColor:C.bg}} contentInsetAdjustmentBehavior="automatic" keyboardShouldPersistTaps="handled" contentContainerStyle={[s.page,{paddingBottom:inset.bottom+32}]}>{children}</ScrollView>;}
export function Body({children}:{children:React.ReactNode}){return <Text selectable style={s.body}>{children}</Text>;}
export function Card({children}:{children:React.ReactNode}){return <View style={s.card}>{children}</View>;}
export function Label({children}:{children:React.ReactNode}){return <Text style={s.label}>{children}</Text>;}
export function Button({title,onPress,secondary=false,disabled=false,testID}:{title:string;onPress:()=>void;secondary?:boolean;disabled?:boolean;testID?:string}){return <Pressable testID={testID} accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,secondary&&{backgroundColor:'#283625',borderWidth:1,borderColor:'#4a5e3c'}, {opacity:disabled ? 0.45 : pressed ? 0.75 : 1}]}><Text style={[s.buttonText,secondary&&{color:C.ink}]}>{title}</Text></Pressable>;}
export function Chips({values,value,onChange}:{values:string[];value:string;onChange:(v:string)=>void}){return <ScrollView horizontal showsHorizontalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={{gap:8,paddingVertical:3}}>{values.map(v=><Pressable key={v} accessibilityRole="button" accessibilityState={{selected:v===value}} onPress={()=>onChange(v)} style={[s.chip,v===value&&{backgroundColor:'#33432a',borderColor:C.lime}]}><Text style={{color:v===value?C.lime:C.muted,fontWeight:'600',fontSize:12}}>{v}</Text></Pressable>)}</ScrollView>;}
export function Field({label,...props}:TextInputProps&{label:string}){return <View style={{gap:7}}><Text style={{fontSize:12,color:C.muted,fontWeight:'700'}}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor="#73816b" {...props} style={[s.input,props.multiline&&{minHeight:94,textAlignVertical:'top'},props.style]}/></View>;}
export function ProductPhoto({product,height=190}:{product:Product;height?:number}){
  const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[product.photo?.url]);
  return <View style={{height,backgroundColor:product.photo&&!failed?'#fff':'#21301e',borderRadius:14,overflow:'hidden',alignItems:'center',justifyContent:'center'}}>{product.photo&&!failed?<Image source={{uri:product.photo.url}} style={{width:'100%',height:'100%'}} contentFit="contain" cachePolicy="none" transition={160} accessibilityLabel={`${product.name} product reference`} onError={()=>setFailed(true)}/>:<View style={{padding:20,gap:9,alignItems:'center'}}><Text style={{fontSize:32,color:C.lime}}>◇</Text><Text style={{color:C.ink,fontWeight:'700'}}>{product.brand}</Text><Text style={s.small}>{failed?'Photo unavailable · open source':'Product photo not added yet'}</Text></View>}</View>;
}
export function ProductCard({product,tripId}:{product:Product;tripId?:string}){return <Link href={{pathname:'/product/[id]',params:{id:product.id,...(tripId?{tripId}:{})}}} asChild><Pressable accessibilityRole="button" accessibilityLabel={`View ${product.name}`} style={({pressed})=>[s.card,{padding:12,opacity:pressed ? 0.8 : 1}]}><ProductPhoto product={product}/><View style={{padding:5,gap:6}}><Label>{product.brand}</Label><Text style={{fontSize:19,fontWeight:'700',color:C.ink}}>{product.model}</Text><Text style={s.small}>{product.variant||product.kind}</Text><View style={[s.row,{justifyContent:'space-between'}]}><Text selectable style={{color:C.ink,fontWeight:'700'}}>{money(product.priceUSD)}</Text><Text selectable style={s.small}>{product.weightGrams===null?'Weight not checked':weight(product.weightGrams)}</Text></View><Text style={{fontSize:10,color:C.muted}}>Reference data · not a live offer</Text></View></Pressable></Link>;}
export function ErrorText({message}:{message:string}){return message?<Text selectable accessibilityRole="alert" style={{color:C.warn,lineHeight:20}}>{message}</Text>:null;}
