import { useState } from 'react';
import { Link, Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { Linking, Text, View } from 'react-native';
import { catalog } from '@/catalog';
import { fromProduct, https, money, weight } from '@/domain';
import { useStore } from '@/store';
import { Body, Button, C, Card, ErrorText, Label, Page, ProductPhoto, s } from '@/ui';
export default function ProductDetail(){const {id,tripId}=useLocalSearchParams<{id:string;tripId?:string}>(),{state,commit,saving}=useStore(),router=useRouter();const [message,setMessage]=useState(''),[chooseTrip,setChooseTrip]=useState(false);const p=catalog.find(x=>x.id===id);
 if(!p)return <Page><Text style={s.h2}>Product not found</Text><Button title="Back to catalog" onPress={()=>router.replace('/catalog')}/></Page>;
 const favorite=state.favorites.includes(id),owned=state.gear.some(g=>g.product?.id===id),trip=state.trips.find(t=>t.id===tripId),variants=catalog.filter(x=>x.brand===p.brand&&x.model===p.model&&x.id!==p.id);
 async function add(target?:string){try{await commit(s=>{const list=target?s.trips.find(t=>t.id===target)?.items:s.gear;if(!list)throw Error('Trip not found.');if(list.some(g=>g.product?.id===p!.id))throw Error('This model/configuration is already here. Edit its quantity instead.');list.push(fromProduct(p!,!target));return s;});setMessage(target?'Added to your trip, not marked owned or packed.':'Saved to your gear locker as owned.');setChooseTrip(false);}catch(e){setMessage(e instanceof Error?e.message:String(e));}}
 async function toggleFavorite(){try{await commit(s=>({...s,favorites:s.favorites.includes(id)?s.favorites.filter(x=>x!==id):[...s.favorites,id]}));}catch(e){setMessage(String(e));}}
 async function open(url:string){try{await Linking.openURL(https(url));}catch{setMessage('Could not open the source. Check your connection and try again.');}}
 return <Page><Stack.Screen options={{title:p.model}}/><ProductPhoto product={p} height={320}/><Label>{p.brand} / {p.kind}</Label><Text style={s.title}>{p.model}</Text><Text selectable style={s.body}>{p.variant||'Select your exact size and configuration with the seller.'}</Text><View style={s.row}><Button secondary title={favorite?'Saved to favorites ♥':'Save favorite ♡'} onPress={()=>void toggleFavorite()} disabled={saving}/></View><Card><Text style={s.small}>Reference weight — not your measured equipment</Text><Text selectable style={s.h2}>{weight(p.weightGrams)}</Text><Text selectable style={s.body}>{p.weightLabel}</Text><Text style={s.small}>{p.weightCheckedAt?`Weight checked against source ${p.weightCheckedAt}.`:'Migrated prototype specification; not independently rechecked in this build.'}</Text><Text selectable style={s.h2}>{money(p.priceUSD)}</Text><Text style={s.small}>Legacy reference price ({p.checkedAt||'date unknown'}), not live pricing. Confirm taxes, shipping, stock and exact option at the seller.</Text></Card><Body>{p.note}</Body>{p.photo?<Card><Label>ABOUT THIS PHOTO</Label><Body>{p.photo.caption}</Body><Text style={s.small}>Manufacturer reference linked {p.photo.checkedAt}. No affiliation or commercial image license is implied. Photos load from the source; they are not bundled offline.</Text></Card>:null}<ErrorText message={message}/><Button title={owned?'Already in your locker':'I own this — add to locker'} onPress={()=>void add()} disabled={owned||saving}/><Button secondary title={trip?`Add to ${trip.name}`:'Add to a trip'} onPress={()=>trip?void add(trip.id):setChooseTrip(!chooseTrip)} disabled={saving}/>{chooseTrip?<Card><Label>CHOOSE A TRIP</Label>{state.trips.map(t=><Button key={t.id} secondary title={t.name} onPress={()=>void add(t.id)} disabled={saving}/>)}{!state.trips.length?<Button title="Build a trip first" onPress={()=>router.push('/trip/new')}/>:null}</Card>:null}{trip?<Link href={{pathname:'/trip/[id]',params:{id:trip.id}}} style={{color:C.lime,padding:10}}>Return to this loadout →</Link>:null}<Button title="View / buy at source ↗" onPress={()=>void open(p.purchaseURL||p.sourceURL)}/><Text style={s.small}>Opens an external seller or brand page. No checkout, commission tracking or purchase happens inside HunterOS. Some legacy links lead to a brand homepage.</Text>{variants.length?<View style={{gap:12}}><Text style={s.h2}>Other configurations</Text>{variants.map(v=><Link key={v.id} href={{pathname:'/product/[id]',params:{id:v.id,...(tripId?{tripId}:{})}}} style={{padding:14,borderWidth:1,borderColor:C.line,borderRadius:12,color:C.lime}}>{v.variant||v.name} →</Link>)}</View>:null}</Page>;
}
