import { useState } from 'react';
import { useRouter } from 'expo-router';
import { Text } from 'react-native';
import { Button, Chips, ErrorText, Field, Label, Page, s } from '@/ui';
import { generateChecklist, STYLES, TRIP_TYPES, uid, validTripDate } from '@/domain';
import { useStore } from '@/store';
import type { Trip, TripType } from '@/types';
export default function NewTrip(){const router=useRouter(),{commit,saving}=useStore();const [type,setType]=useState<TripType>('Hunting + Camping'),[style,setStyle]=useState<Trip['style']>('Backcountry'),[name,setName]=useState(''),[region,setRegion]=useState('Colorado'),[area,setArea]=useState(''),[date,setDate]=useState(''),[days,setDays]=useState('5'),[people,setPeople]=useState('1'),[species,setSpecies]=useState('Elk'),[low,setLow]=useState('25'),[high,setHigh]=useState('60'),[notes,setNotes]=useState(''),[error,setError]=useState('');
 async function save(){setError('');try{if(!name.trim()||!region.trim())throw Error('Enter a trip name and region.');if(!validTripDate(date))throw Error('Enter a real calendar date in YYYY-MM-DD format, or leave it blank.');if(!days.trim()||!people.trim()||!low.trim()||!high.trim())throw Error('Enter days, people and your temperature assumptions.');const t:Trip={id:uid(),name:name.trim(),region:region.trim(),type,style,area,date,days:Number(days),people:Number(people),species,low:Number(low),high:Number(high),notes,items:generateChecklist(type,style,Number(days))};await commit(s=>({...s,trips:[t,...s.trips]}));router.replace({pathname:'/trip/[id]',params:{id:t.id}});}catch(e){setError(e instanceof Error?e.message:String(e));}}
 return <Page><Label>01 / THE ADVENTURE</Label><Text style={s.title}>{'Start with where\nyou’re going.'}</Text><Text style={s.body}>No account required. Every trip gets its own checklist.</Text><Chips values={TRIP_TYPES} value={type} onChange={v=>setType(v as TripType)}/><Field label="Trip name" placeholder="Fall elk camp" value={name} onChangeText={setName} maxLength={200}/><Field label="State / region" value={region} onChangeText={setRegion} maxLength={200}/><Field label="Camp, trailhead or area" value={area} onChangeText={setArea} placeholder="Optional. Not a map pin." maxLength={300}/><Field label="Start date (YYYY-MM-DD)" value={date} onChangeText={setDate} placeholder="Optional" autoCapitalize="none" maxLength={10}/><Field label="Number of days" value={days} onChangeText={setDays} keyboardType="number-pad" maxLength={2}/><Field label="People on trip" value={people} onChangeText={setPeople} keyboardType="number-pad" maxLength={2}/><Label>02 / YOUR SETUP</Label><Chips values={[...STYLES]} value={style} onChange={v=>setStyle(v as Trip['style'])}/>{(type==='Hunting'||type==='Hunting + Camping')?<Field label="Species" value={species} onChangeText={setSpecies} maxLength={80}/>:null}<Field label="Expected low °F (your assumption)" value={low} onChangeText={setLow} keyboardType="numbers-and-punctuation" maxLength={4}/><Field label="Expected high °F (your assumption)" value={high} onChangeText={setHigh} keyboardType="numbers-and-punctuation" maxLength={4}/><Text style={s.small}>25–60°F are example values, not a forecast or a safe gear rating. Adjust for your trip.</Text><Field label="Trip notes / check-in plan" value={notes} onChangeText={setNotes} multiline maxLength={5000}/><ErrorText message={error}/><Button testID="create-trip" title={saving?'Saving…':'Create trip'} disabled={saving} onPress={()=>void save()}/></Page>;
}
